// <auto-generated />
using System;
using AgenciaViagem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgenciaViagem.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgenciaViagem.Models.CadastrarCliente", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cidade_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_nasc_cliente")
                        .HasColumnType("datetime2");

                    b.Property<string>("email_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobrenome_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_cliente");

                    b.ToTable("cadastrarClientes");
                });

            modelBuilder.Entity("AgenciaViagem.Models.CompraCliente", b =>
                {
                    b.Property<int>("Id_compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dia_chegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dia_ida")
                        .HasColumnType("datetime2");

                    b.Property<string>("local_chegada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("local_partida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("num_assento")
                        .HasColumnType("int");

                    b.Property<int>("qtd_passagem")
                        .HasColumnType("int");

                    b.Property<string>("sobrenome_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_compra");

                    b.ToTable("compraClientes");
                });

            modelBuilder.Entity("AgenciaViagem.Models.ContatoCliente", b =>
                {
                    b.Property<int>("Id_contato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cidade_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motivo_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regiao_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobrenome_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone_contato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_contato");

                    b.ToTable("contatoClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
